#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

GAMES=(wow)

function one {
  export GAME="$1"
  echo "Building $GAME"
  rm -rf "www/${GAME}"
  mkdir "www/${GAME}"
  echo "import main from './src/${GAME}.js'; main();" | npx rollup -c rollup.mjs
  node process.mjs
  rm -f "www/${GAME}/bundle.js"
}

function rebuild {
  rm -rf www/
  mkdir www/
  build
}

function build {
  \cp page.html www/index.html
  \cp icon.png www/

  for g in ${GAMES[@]}; do
    if [ ! -d "www/$g" ]; then
      one "$g"
    else
      echo "Skipping $g"
    fi
  done
}

function sync {
  rsync -a --partial --progress www/ metaphora.co:one/
}

function help {
  echo "$0 <task> <args>"
  echo "Tasks:"
  compgen -A function | grep -v "^_" | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-help}"